# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd8a3f97c4c6696de696cef3ec313e4ca4833919a2d757661bb4df6cffeff901ce3845612019044a7b0c1d59c96b6b812659e5e3f3248fe6eb0661fcd0e92ac6

test:
  secret_key_base: adb45651f2ecb5f1aac8f0d617279b5c9ddc899c6f734ec19afbf2a3e4d4ab02052ec7aa3d9aa7c016dea355c64d5acfaf2cf00c6b19f44c8e0e054c270edfbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
